server:
  port: 8088
spring:
  application:
    name: feedback-service
  datasource:
    url: jdbc:postgresql://localhost:5438/feedback_db
    username: bookstore
    password: bookstore123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
